name: Deploy on DEV
# This workflow is triggered on PRs
on:
  pull_request:
    branches:
      - $default-branch

permissions:
  contents: write
  pull-requests: write
  packages: read

env:
  REGION: us-east-1 # Dev Region

jobs:
  auto-merge-dependabot:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    uses: Bastion-Technologies/github_workflows/.github/workflows/aws-ci.yml@main
    with:
      region: us-east-1
    secrets:
      AWS_CICD_ROLE: ${{ secrets.AWS_CICD_DEV_ROLE }}
      AWS_CICD_ACCESS_KEY: ${{ secrets.AWS_CICD_ACCESS_KEY }}
      AWS_CICD_SECRET_KEY: ${{ secrets.AWS_CICD_SECRET_KEY }}
