name: Deploy on DEV
# This workflow is triggered on PRs
on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

env:
  REGION: us-east-1 # Dev Region

jobs:
  deploy:
    name: Build And Deploy

    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CICD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_CICD_SECRET_KEY }}
          aws-region: ${{ env.REGION }}
          role-to-assume: ${{ secrets.AWS_CICD_DEV_ROLE }}
          role-duration-seconds: 1200
          role-session-name: GitActionDeploymentSession

      - name: Prerequisite Installation
        run: npm install -g aws-cdk

      - name: Build & Deploy
        run: |
          cd $GITHUB_WORKSPACE
          ls -a
          chmod 700 deploy.sh
          ./deploy.sh
